# Generated by Django 2.1.4 on 2019-02-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_cafes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Cafe')),
                ('saved_hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Hotel')),
            ],
        ),
    ]
