# Generated by Django 2.1.4 on 2019-02-22 04:37

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('building_number', models.CharField(blank=True, max_length=3)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('locality', models.CharField(blank=True, default='', max_length=50)),
                ('headers', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('center_related', models.CharField(blank=True, default='', max_length=50)),
                ('mark', models.FloatField(default=0.0)),
                ('img_url', models.CharField(default='', max_length=512, null=True)),
                ('users_saved', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address_raw_line', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=1024)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('opening_hour', models.TimeField(default=datetime.time(9, 0))),
                ('closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.FloatField(default=0.0)),
                ('catering_type', models.CharField(choices=[('RESTAURANT', 'restaurant'), ('CAFE', 'cafe'), ('COFFEE BREAK', 'coffee break'), ('BAKERY', 'bakery'), ('BAR', 'bar')], default='RESTAURANT', max_length=10)),
                ('cuisine', models.CharField(choices=[('UKRAINIAN', 'Ukrainian'), ('ITALIAN', 'Italian'), ('ASIAN', 'Asian'), ('AMERICAN', 'American'), ('CHINESE', 'Chinese')], default='UKRAINIAN', max_length=9)),
                ('dietary', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('CARNIVOROUS', 'Carnivorous')], default='CARNIVOROUS', max_length=11)),
                ('time_of_day', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('SNACK', 'Snack'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default='BREAKFAST', max_length=9)),
                ('portion_size', models.CharField(choices=[('BITE', 'bite'), ('MEDIUM', 'medium'), ('SQUARE MEAL', 'square meal'), ('FAMILY LUNCH', 'family lunch'), ('BANQUET', 'banquet')], default='BITE', max_length=12)),
                ('img_url', models.CharField(default='', max_length=512, null=True)),
                ('image_uploaded_by_user', models.ImageField(blank=True, null=True, upload_to='images/places_imgs/foodplaces')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'foodplace',
                'verbose_name_plural': 'foodplaces',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.CharField(blank=True, default='', max_length=1024)),
                ('phone', models.IntegerField(blank=True, help_text='Please use the following format: 380123456789', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('mark', models.FloatField(default=0.0)),
                ('children_allowed', models.BooleanField(default=False, null=True)),
                ('pets_allowed', models.BooleanField(null=True)),
                ('has_restaurant', models.BooleanField(default=False, null=True)),
                ('has_pool', models.BooleanField(default=False, null=True)),
                ('has_spa', models.BooleanField(default=False, null=True)),
                ('shuttle', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('img_url', models.CharField(default='', max_length=512, null=True)),
                ('image_uploaded_by_user', models.ImageField(blank=True, null=True, upload_to='images/places_imgs/hotels')),
                ('address_raw_line', models.CharField(blank=True, default='', max_length=255)),
                ('users_saved', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.Hotel'),
        ),
        migrations.AddField(
            model_name='address',
            name='foodplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodplace_address', to='places.FoodPlace'),
        ),
        migrations.AddField(
            model_name='address',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_address', to='places.Hotel'),
        ),
    ]
